language: node_js
node_js:
- '0.12'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: mvila@3base.com
  api_key:
    secure: NAHuWY75cDwEGv/JPmXgYslybhtOUlcE71vrrF1NDejzRwvkbfsjwlxmLRADaE9/iwd+X1kG+CEIiANnEOuOJxpd0BNHAKSU7h0vfOcZ8gwTyfFK99IDE0lzrW/IlJPcLR52MqFVBGGZuexhNH34rrYhcOxx/UOBj+n5DhzfyVE=
  skip_cleanup: true
notifications:
  email: false
  slack:
    secure: B7SzTnNXvsI2ahNE+mehVzMSDMVQCmMfiaOKFiW6mVHb9XvG9kRKiQwKYkEAwEuFgctBnLhBBBgRy+5u5VqO2guoXRbzyJW9OlDIn3x3P77SlstWoqdGuiHQ7sS+Upd/2RvaFj5BvXgBLheWLypihLqDSlU+pUx2d1M0B9hKXsA=
sudo: false
